In [12]:
import pandas as pd
import numpy as np
import random

In [356]:
#make a random array, x[0] = 1, x[i] = x[i-1] + random.uniform(-1, 1)
def random_array(M):
    #random.seed(42)
    N=1024
    x = range(N)
    y = np.zeros(N*M)
    y[0] = 1
    for i in range(1, N*M):
        y[i] = y[i-1] + random.uniform(-1, 1)
    
    return y

In [357]:
y = random_array(1000)
y

array([   1.        ,    1.11425382,    1.45094022, ..., -856.78199994,
       -857.64526081, -857.91306294])

In [100]:
#lokal maxima without conditions
def maxima(x, arr):
    #distance between min/max
    dist = x
    #an array of zeros
    array = np.zeros(len(arr))
    #if local maxima, than 1
    for i in range(1, len(arr)-1):
        if dist > x:
            if arr[i] > arr[i-1] and arr[i] > arr[i+1]:
                dist = 1
                array[i] = 1
        else:
            dist+=1
    return array
        

In [362]:
#lokal maxima/minima of random_array M*1024 
#with distance between extrema > 3
#changing MAXs and MINs
#with T*std so that there approx. 10 extrema in N=1024

def extrema(x, M=3000):
    arr = random_array(M)
    #flag variable
    found_min = False
    found = False
    #1/4 of std 
    T = 0.25
    #distance between extrema >3
    dist = x+1
    Ymax = np.zeros(len(arr))
    Ymin = np.zeros(len(arr))
    #T*std
    D = T*np.std(arr[:-(len(arr)-1)] - arr[0:])
    for i in range(1, len(arr)-1):
        #print(D)
        #dist > 3 
        if dist > x and dist>=D:
            #decides to start with MAX or MIN at the beginning of the search
            if found_min or not found:
                if arr[i] > arr[i-1] and arr[i] > arr[i+1]:
                    dist = 1
                    Ymax[i] = 1
                    found = True
                    found_min = False
            if not found_min or not found:
                if arr[i] < arr[i-1] and arr[i] < arr[i+1]:
                        dist = 1
                        Ymin[i] = 1
                        found = True
                        found_min = True 
        else:
            dist+=1
    #Y_mean = number of extrema in N=1024       
    Y_mean = np.sum(np.r_[Ymax, Ymin])/M
    return Ymax, Ymin, Y_mean



In [363]:
extrema(3)

(array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 12.800666666666666)